import csv

inp_str = """logo url for 50: https://media-4.api-sports.io/football/teams/50.png
logo url for 42: https://media-4.api-sports.io/football/teams/42.png
logo url for 33: https://media-4.api-sports.io/football/teams/33.png
logo url for 34: https://media-4.api-sports.io/football/teams/34.png
logo url for 40: https://media-4.api-sports.io/football/teams/40.png
logo url for 51: https://media-4.api-sports.io/football/teams/51.png
logo url for 66: https://media-4.api-sports.io/football/teams/66.png
logo url for 47: https://media-4.api-sports.io/football/teams/47.png
logo url for 55: https://media-4.api-sports.io/football/teams/55.png
logo url for 36: https://media-4.api-sports.io/football/teams/36.png
logo url for 52: https://media-4.api-sports.io/football/teams/52.png
logo url for 49: https://media-4.api-sports.io/football/teams/49.png
logo url for 39: https://media-4.api-sports.io/football/teams/39.png
logo url for 48: https://media-4.api-sports.io/football/teams/48.png
logo url for 35: https://media-4.api-sports.io/football/teams/35.png
logo url for 65: https://media-4.api-sports.io/football/teams/65.png
logo url for 45: https://media-4.api-sports.io/football/teams/45.png
logo url for 46: https://media-4.api-sports.io/football/teams/46.png
logo url for 63: https://media-4.api-sports.io/football/teams/63.png
logo url for 41: https://media-4.api-sports.io/football/teams/41.png
logo url for 529: https://media-4.api-sports.io/football/teams/529.png
logo url for 541: https://media-4.api-sports.io/football/teams/541.png
logo url for 530: https://media-4.api-sports.io/football/teams/530.png
logo url for 548: https://media-4.api-sports.io/football/teams/548.png
logo url for 533: https://media-4.api-sports.io/football/teams/533.png
logo url for 543: https://media-4.api-sports.io/football/teams/543.png
logo url for 727: https://media-4.api-sports.io/football/teams/727.png
logo url for 531: https://media-4.api-sports.io/football/teams/531.png
logo url for 798: https://media-4.api-sports.io/football/teams/798.png
logo url for 547: https://media-4.api-sports.io/football/teams/547.png
logo url for 728: https://media-4.api-sports.io/football/teams/728.png
logo url for 536: https://media-4.api-sports.io/football/teams/536.png
logo url for 538: https://media-4.api-sports.io/football/teams/538.png
logo url for 724: https://media-4.api-sports.io/football/teams/724.png
logo url for 546: https://media-4.api-sports.io/football/teams/546.png
logo url for 532: https://media-4.api-sports.io/football/teams/532.png
logo url for 723: https://media-4.api-sports.io/football/teams/723.png
logo url for 720: https://media-4.api-sports.io/football/teams/720.png
logo url for 540: https://media-4.api-sports.io/football/teams/540.png
logo url for 797: https://media-4.api-sports.io/football/teams/797.png
logo url for 157: https://media-4.api-sports.io/football/teams/157.png
logo url for 165: https://media-4.api-sports.io/football/teams/165.png
logo url for 173: https://media-4.api-sports.io/football/teams/173.png
logo url for 182: https://media-4.api-sports.io/football/teams/182.png
logo url for 160: https://media-4.api-sports.io/football/teams/160.png
logo url for 168: https://media-4.api-sports.io/football/teams/168.png
logo url for 169: https://media-4.api-sports.io/football/teams/169.png
logo url for 161: https://media-4.api-sports.io/football/teams/161.png
logo url for 164: https://media-4.api-sports.io/football/teams/164.png
logo url for 163: https://media-4.api-sports.io/football/teams/163.png
logo url for 192: https://media-4.api-sports.io/football/teams/192.png
logo url for 167: https://media-4.api-sports.io/football/teams/167.png
logo url for 162: https://media-4.api-sports.io/football/teams/162.png
logo url for 176: https://media-4.api-sports.io/football/teams/176.png
logo url for 170: https://media-4.api-sports.io/football/teams/170.png
logo url for 172: https://media-4.api-sports.io/football/teams/172.png
logo url for 174: https://media-4.api-sports.io/football/teams/174.png
logo url for 159: https://media-4.api-sports.io/football/teams/159.png
logo url for 209: https://media-4.api-sports.io/football/teams/209.png
logo url for 197: https://media-4.api-sports.io/football/teams/197.png
logo url for 194: https://media-4.api-sports.io/football/teams/194.png
logo url for 201: https://media-4.api-sports.io/football/teams/201.png
logo url for 415: https://media-4.api-sports.io/football/teams/415.png
logo url for 426: https://media-4.api-sports.io/football/teams/426.png
logo url for 207: https://media-4.api-sports.io/football/teams/207.png
logo url for 210: https://media-4.api-sports.io/football/teams/210.png
logo url for 417: https://media-4.api-sports.io/football/teams/417.png
logo url for 200: https://media-4.api-sports.io/football/teams/200.png
logo url for 410: https://media-4.api-sports.io/football/teams/410.png
logo url for 413: https://media-4.api-sports.io/football/teams/413.png
logo url for 205: https://media-4.api-sports.io/football/teams/205.png
logo url for 416: https://media-4.api-sports.io/football/teams/416.png
logo url for 196: https://media-4.api-sports.io/football/teams/196.png
logo url for 208: https://media-4.api-sports.io/football/teams/208.png
logo url for 420: https://media-4.api-sports.io/football/teams/420.png
logo url for 202: https://media-4.api-sports.io/football/teams/202.png
logo url for 492: https://media-4.api-sports.io/football/teams/492.png
logo url for 487: https://media-4.api-sports.io/football/teams/487.png
logo url for 505: https://media-4.api-sports.io/football/teams/505.png
logo url for 489: https://media-4.api-sports.io/football/teams/489.png
logo url for 499: https://media-4.api-sports.io/football/teams/499.png
logo url for 497: https://media-4.api-sports.io/football/teams/497.png
logo url for 496: https://media-4.api-sports.io/football/teams/496.png
logo url for 502: https://media-4.api-sports.io/football/teams/502.png
logo url for 500: https://media-4.api-sports.io/football/teams/500.png
logo url for 503: https://media-4.api-sports.io/football/teams/503.png
logo url for 1579: https://media-4.api-sports.io/football/teams/1579.png
logo url for 494: https://media-4.api-sports.io/football/teams/494.png
logo url for 488: https://media-4.api-sports.io/football/teams/488.png
logo url for 511: https://media-4.api-sports.io/football/teams/511.png
logo url for 514: https://media-4.api-sports.io/football/teams/514.png
logo url for 867: https://media-4.api-sports.io/football/teams/867.png
logo url for 515: https://media-4.api-sports.io/football/teams/515.png
logo url for 504: https://media-4.api-sports.io/football/teams/504.png
logo url for 520: https://media-4.api-sports.io/football/teams/520.png
logo url for 498: https://media-4.api-sports.io/football/teams/498.png
logo url for 85: https://media-4.api-sports.io/football/teams/85.png
logo url for 116: https://media-4.api-sports.io/football/teams/116.png
logo url for 81: https://media-4.api-sports.io/football/teams/81.png
logo url for 94: https://media-4.api-sports.io/football/teams/94.png
logo url for 79: https://media-4.api-sports.io/football/teams/79.png
logo url for 91: https://media-4.api-sports.io/football/teams/91.png
logo url for 80: https://media-4.api-sports.io/football/teams/80.png
logo url for 99: https://media-4.api-sports.io/football/teams/99.png
logo url for 84: https://media-4.api-sports.io/football/teams/84.png
logo url for 97: https://media-4.api-sports.io/football/teams/97.png
logo url for 93: https://media-4.api-sports.io/football/teams/93.png
logo url for 82: https://media-4.api-sports.io/football/teams/82.png
logo url for 96: https://media-4.api-sports.io/football/teams/96.png
logo url for 106: https://media-4.api-sports.io/football/teams/106.png
logo url for 95: https://media-4.api-sports.io/football/teams/95.png
logo url for 83: https://media-4.api-sports.io/football/teams/83.png
logo url for 108: https://media-4.api-sports.io/football/teams/108.png
logo url for 98: https://media-4.api-sports.io/football/teams/98.png
logo url for 110: https://media-4.api-sports.io/football/teams/110.png
logo url for 77: https://media-4.api-sports.io/football/teams/77.png
logo url for 211: https://media-4.api-sports.io/football/teams/211.png
logo url for 212: https://media-4.api-sports.io/football/teams/212.png
logo url for 217: https://media-4.api-sports.io/football/teams/217.png
logo url for 228: https://media-4.api-sports.io/football/teams/228.png
logo url for 240: https://media-4.api-sports.io/football/teams/240.png
logo url for 224: https://media-4.api-sports.io/football/teams/224.png
logo url for 223: https://media-4.api-sports.io/football/teams/223.png
logo url for 242: https://media-4.api-sports.io/football/teams/242.png
logo url for 222: https://media-4.api-sports.io/football/teams/222.png
logo url for 4716: https://media-4.api-sports.io/football/teams/4716.png
logo url for 810: https://media-4.api-sports.io/football/teams/810.png
logo url for 226: https://media-4.api-sports.io/football/teams/226.png
logo url for 762: https://media-4.api-sports.io/football/teams/762.png
logo url for 230: https://media-4.api-sports.io/football/teams/230.png
logo url for 216: https://media-4.api-sports.io/football/teams/216.png
logo url for 214: https://media-4.api-sports.io/football/teams/214.png
logo url for 234: https://media-4.api-sports.io/football/teams/234.png
logo url for 227: https://media-4.api-sports.io/football/teams/227.png
logo url for 1599: https://media-4.api-sports.io/football/teams/1599.png
logo url for 1614: https://media-4.api-sports.io/football/teams/1614.png
logo url for 1604: https://media-4.api-sports.io/football/teams/1604.png
logo url for 1602: https://media-4.api-sports.io/football/teams/1602.png
logo url for 2242: https://media-4.api-sports.io/football/teams/2242.png
logo url for 9568: https://media-4.api-sports.io/football/teams/9568.png
logo url for 1598: https://media-4.api-sports.io/football/teams/1598.png
logo url for 1613: https://media-4.api-sports.io/football/teams/1613.png
logo url for 18310: https://media-4.api-sports.io/football/teams/18310.png
logo url for 1609: https://media-4.api-sports.io/football/teams/1609.png
logo url for 1608: https://media-4.api-sports.io/football/teams/1608.png
logo url for 1607: https://media-4.api-sports.io/football/teams/1607.png
logo url for 1601: https://media-4.api-sports.io/football/teams/1601.png
logo url for 1615: https://media-4.api-sports.io/football/teams/1615.png"""
tids = []
urls = []
for x in inp_str.split():
    if str.isdigit(x.strip(":")):
        tids.append(x.strip(":"))
    elif x[:3] == "htt":
        urls.append(x)

with open("ids_and_urls.csv", "w") as f:
    writer = csv.writer(f)
    for team_id, url in zip(tids, urls):
        writer.writerow([team_id, url])